// <auto-generated />
using System;
using Anotai.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anotai.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220318113653_Creating Gender Default")]
    partial class CreatingGenderDefault
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Anotai.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4978),
                            Description = "AÇÃO E AVENTURA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4988)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4991),
                            Description = "ARTE E FOTOGRAFIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4992)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4993),
                            Description = "AUTOAJUDA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4994)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4995),
                            Description = "BIOGRAFIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4996)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4998),
                            Description = "CONTO",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(4998)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5000),
                            Description = "CRIMES REAIS",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5001)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5002),
                            Description = "DISTOPIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5003)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5004),
                            Description = "ENSAIOS",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5005)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5006),
                            Description = "FANTASIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5007)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5008),
                            Description = "FICÇÃO CIENTÍFICA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5009)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5010),
                            Description = "FICÇÃO CONTEMPORÂNEA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5011)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5012),
                            Description = "FICÇÃO FEMININA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5013)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5015),
                            Description = "FICÇÃO HISTÓRICA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5016)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5017),
                            Description = "FICÇÃO POLICIAL",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5018)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5020),
                            Description = "GASTRONOMIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5020)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5022),
                            Description = "GÊNEROS DE FICÇÃO",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5022)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5024),
                            Description = "GÊNEROS DE NÃO FICÇÃO",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5025)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5026),
                            Description = "GRAPHIC NOVEL",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5027)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5028),
                            Description = "GUIAS & COMO FAZER ",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5029)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5030),
                            Description = "HISTÓRIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5031)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5032),
                            Description = "HORROR",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5033)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5035),
                            Description = "HUMANIDADES E CIÊNCIAS SOCIAIS",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5035)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5037),
                            Description = "HUMOR",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5037)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5039),
                            Description = "INFANTIL",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5039)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5041),
                            Description = "INFANTIL",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5042)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5043),
                            Description = "LGBTQ+",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5044)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5045),
                            Description = "MEMÓRIAS E AUTOBIOGRAFIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5046)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5048),
                            Description = "NEW ADULT – NOVO ADULTO ",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5048)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5049),
                            Description = "PATERNIDADE E FAMÍLIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5050)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5052),
                            Description = "REALISMO MÁGICO",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5052)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5054),
                            Description = "RELIGIÃO E ESPIRITUALIDADE",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5054)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5056),
                            Description = "ROMANCE",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5056)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5058),
                            Description = "TECNOLOGIA E CIÊNCIA",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5058)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5060),
                            Description = "THRILLER E SUSPENSE",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5060)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5062),
                            Description = "VIAJEM",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5063)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5064),
                            Description = "YOUNG ADULT – JOVEM ADULTO",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2022, 3, 18, 8, 36, 53, 577, DateTimeKind.Local).AddTicks(5065)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
