// <auto-generated />
using System;
using Anotai.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anotai.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220321190710_Updated At Is Null Extentions")]
    partial class UpdatedAtIsNullExtentions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Anotai.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2502));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2786),
                            Description = "AÇÃO E AVENTURA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2792),
                            Description = "ARTE E FOTOGRAFIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2793),
                            Description = "AUTOAJUDA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2795),
                            Description = "BIOGRAFIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2796),
                            Description = "CONTO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2798),
                            Description = "CRIMES REAIS",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2799),
                            Description = "DISTOPIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2801),
                            Description = "ENSAIOS",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2802),
                            Description = "FANTASIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2803),
                            Description = "FICÇÃO CIENTÍFICA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2805),
                            Description = "FICÇÃO CONTEMPORÂNEA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2806),
                            Description = "FICÇÃO FEMININA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2808),
                            Description = "FICÇÃO HISTÓRICA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2809),
                            Description = "FICÇÃO POLICIAL",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2811),
                            Description = "GASTRONOMIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2812),
                            Description = "GÊNEROS DE FICÇÃO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2814),
                            Description = "GÊNEROS DE NÃO FICÇÃO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2815),
                            Description = "GRAPHIC NOVEL",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2816),
                            Description = "GUIAS & COMO FAZER ",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2818),
                            Description = "HISTÓRIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2819),
                            Description = "HORROR",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2821),
                            Description = "HUMANIDADES E CIÊNCIAS SOCIAIS",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2822),
                            Description = "HUMOR",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2823),
                            Description = "INFANTIL",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2825),
                            Description = "LGBTQ+",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2826),
                            Description = "MEMÓRIAS E AUTOBIOGRAFIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2829),
                            Description = "NEW ADULT – NOVO ADULTO ",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2830),
                            Description = "PATERNIDADE E FAMÍLIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2831),
                            Description = "REALISMO MÁGICO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2833),
                            Description = "RELIGIÃO E ESPIRITUALIDADE",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2834),
                            Description = "ROMANCE",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2835),
                            Description = "TECNOLOGIA E CIÊNCIA",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2837),
                            Description = "THRILLER E SUSPENSE",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2838),
                            Description = "VIAJEM",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2022, 3, 21, 16, 7, 10, 533, DateTimeKind.Local).AddTicks(2839),
                            Description = "YOUNG ADULT – JOVEM ADULTO",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
